### ISSUE TITLE
Wrong latitude when extracting xarray files 

### ISSUE THREAD

**Issue by arashmodrad** [LynkerIntel/climatePy#12]
Just notice that as I tried clipping the xarray output the latitudes are all negative. For the same example san_luis_obispo_county.gpkg the polygon bounds are  

![image](https://github.com/LynkerIntel/climatePy/assets/55070201/d00fbced-984c-47f5-871e-ed88e76257a4)
 
while the xarray bounds are

![image](https://github.com/LynkerIntel/climatePy/assets/55070201/36734281-559f-496a-a0bc-3532961e388a)

while both are in 'epsg:4326'  CRS               notice the all latitudes are negative in xarray object

**Comment by anguswg-ucsb** [comment]
Thank you @arashmodrad for bringing this to my attention. I am currently working to fix this problem!

**Comment by anguswg-ucsb** [comment]
> Thank you @arashmodrad for bringing this to my attention. I am currently working to fix this problem!

This issue looks to be cleared up with most recent update in version 0.4.37
